# Generated by Django 5.1.4 on 2025-01-03 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Sportliche Kondition',
                'verbose_name_plural': 'Sportliche Konditionen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Sportart',
                'verbose_name_plural': 'Sportart',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Muskelgruppe',
                'verbose_name_plural': 'Muskelgruppen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Datum')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('app', models.TextField(blank=True, null=True, verbose_name='App')),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Distanz')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Dauer')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Datum d. Erstellung')),
                ('conditions', models.ManyToManyField(blank=True, to='fitness.condition', verbose_name='Sportliche Kondition')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitness.discipline')),
                ('muscle_groups', models.ManyToManyField(blank=True, to='fitness.musclegroup', verbose_name='Muskelgruppe')),
            ],
            options={
                'ordering': ['-date', 'name'],
            },
        ),
    ]
