# Generated by Django 5.1.4 on 2025-01-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discipline',
            new_name='Activity',
        ),
    ]
